name: deploy
on:
  registry_package:
    types: [published]


env:
  GCP_ARTIFACT_REGISTRY: 'europe-west1-docker.pkg.dev'
  GCP_ARTIFACT_REGISTRY_REPONAME: 'docker-registry'
  GCP_MAIN_SERVICE_NAME: 'fastapi-template-main'
  GCP_DEV_SERVICE_NAME: 'fastapi-template-dev'
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.event.registry_package.tag_name }}
  GHR_IMAGE: ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GCP login
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        token_format: 'access_token'  # do auth + generate token to be used later
        access_token_lifetime: '300s'

    - name: Get GCP Artifact Registry image name
      id: 'gcp'
      run: |
        echo "GCP_IMAGE=${{ env.GCP_ARTIFACT_REGISTRY }}/${{ steps.auth.outputs.project_id }}/${{ env.GCP_ARTIFACT_REGISTRY_REPONAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

    - name: Docker login
      uses: 'docker/login-action@v1'
      with:
        registry: ${{ env.GCP_ARTIFACT_REGISTRY }}
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: Pull image from GHR
      run: docker pull ${{ env.GHR_IMAGE }}

    - name: Push the same image to Google Artifact Registry
      run: |
        docker tag ${{ env.GHR_IMAGE }} ${{ env.GCP_IMAGE }}
        docker push ${{ env.GCP_IMAGE }}

    - name: Deploy Cloud Run Dev Service
      uses: 'google-github-actions/deploy-cloudrun@v0'
      if: ${{ env.IMAGE_TAG }} == 'dev'
      with:
        service: ${{ GCP_DEV_SERVICE_NAME }}
        image: ${{ env.GCP_IMAGE }}
        region: europe-west1

    - name: Deploy Cloud Run Main Service
      uses: 'google-github-actions/deploy-cloudrun@v0'
      if: ${{ env.IMAGE_TAG }} == 'main'
      with:
        service: ${{ GCP_MAIN_SERVICE_NAME }}
        image: ${{ env.GCP_IMAGE }}
        region: europe-west1